# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FAO Portugal Newsletter
email: proj.faoportugal@gmail.com
url: "https://faoportugal.github.io" # the base hostname & protocol

# Build settings
markdown: kramdown
